name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container: creiterer/cpp-buildenv:latest

    steps:
    - uses: actions/checkout@v1
    - name: Initialize Build
      run: |
        ls
        cd ..
        ls
        bash prol16-tools/initBuild.sh
        ls
    - name: Build
      run: |
        ls
        cd build_prol16-tools
        ls
        ninja -j4
    - name: Test
      run: ctest --output-on-failure
