name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container: creiterer/cpp-buildenv:latest

    steps:
    - uses: actions/checkout@v1
    - name: Initialize Build
      run: bash prol16-tools/initBuild.sh
      working-directory: ../
    - name: Build
      run: ninja
      working-directory: ../build_prol16-tools
    - name: Test
      run: ctest --output-on-failure
      working-directory: ../build_prol16-tools
